package com.texa.carelib.communication;

import android.util.SparseArray;

/* JADX INFO: loaded from: classes2.dex */
public final class Commands {
    public static final int AccelerometerSampleTransmission = 129;
    public static final int AuthenticationRequest = 163;
    public static final int BeginFileDataCrash = 55;
    public static final int BeginFileDataTrip = 52;
    public static final int BeginFileDownload = 48;
    public static final int BeginFileTripDataLog = 255;
    public static final int BeginFileUpdate = 70;
    public static final int BeginSession = 69;
    public static final int CheckOBD = 113;
    public static final int CheckSessionKey = 72;
    public static final int CreateAuthenticationKey = 162;
    public static final int DPMC_GetCreationDate = 220;
    public static final int DPMC_GetSupportedDiagnosticProcedures = 215;
    public static final int DPMC_SetUnlockCode = 217;
    public static final int DPMC_SetUserCode = 216;
    public static final int DPMT_GetMasterRequest = 213;
    public static final int DPMT_NotifySlaveEvent = 219;
    public static final int DPMT_SendSlaveRequest = 214;
    public static final int DPMT_SetNotification = 218;
    public static final int DPM_Call = 211;
    public static final int DPM_EraseECUProgrammingReportFile = 244;
    public static final int DPM_Exit = 212;
    public static final int DPM_GetStatus = 208;
    public static final int DPM_Start = 209;
    public static final int DPM_Stop = 210;
    public static final int EndFileDownload = 51;
    public static final int EndFileUpdate = 75;
    public static final int EraseConfigurationFileArea = 74;
    public static final int EraseCrashDataArea = 56;
    public static final int EraseTripDataArea = 53;
    public static final int GetAvailableParameters = 46;
    public static final int GetBTMacAddress = 233;
    public static final int GetConfigurationID = 77;
    public static final int GetConfigurationPercent = 73;
    public static final int GetCrashConfigurationParameters = 91;
    public static final int GetDataBaseVersion = 67;
    public static final int GetDataManagerParameters = 83;
    public static final int GetDiagnosisMode = 17;
    public static final int GetEraseTripCrashStatus = 100;
    public static final int GetErrorTripData = 98;
    public static final int GetExtractionInsertionTime = 112;
    public static final int GetFileCrashData = 57;
    public static final int GetFileData = 49;
    public static final int GetFileTripData = 54;
    public static final int GetFirmwareStatus = 65;
    public static final int GetFirmwareVersion = 236;
    public static final int GetHardwareVersion = 234;
    public static final int GetInterpreterVersion = 79;
    public static final int GetLog = 118;
    public static final int GetLowPowerRecentHistogram = 116;
    public static final int GetLowPowerTotalHistogram = 117;
    public static final int GetNumSubscribedObjects = 36;
    public static final int GetObjectsValue = 47;
    public static final int GetObjectsValueExt = 43;
    public static final int GetOperatingCrankReport = 115;
    public static final int GetPDUResponses = 35;
    public static final int GetRotationMatrix = 146;
    public static final int GetRotationMatrixStatus = 145;
    public static final int GetRpmSpeedIsValid = 176;
    public static final int GetSOSStatus = 240;
    public static final int GetSerialNumber = 238;
    public static final int GetSessionID = 78;
    public static final int GetSettings = 237;
    public static final int GetStandByCrankReport = 114;
    public static final int GetStartTripData = 96;
    public static final int GetStatisticDiffTripData = 101;
    public static final int GetStatisticsTripData = 99;
    public static final int GetStatus = 230;
    public static final int GetStopTripData = 97;
    public static final int GetSupportedCommands = 239;
    public static final int GetSupportedECU = 85;
    public static final int GetSupportedParameters = 44;
    public static final int GetTripStatus = 231;
    public static final int GetUserDatabase = 242;
    public static final int GetVIN = 45;
    public static final int GetWorkingParameters = 81;
    public static final int KeepAlive = 112;
    public static final int LoadDTCbyECUIndex = 86;
    public static final String NO_NAME = "NO_NAME";
    public static final int ReadDTC = 87;
    public static final int ResetToFactoryDefault = 192;
    public static final int SendFileData = 71;
    public static final int SetAccelerometerSampleConfig = 130;
    public static final int SetConfigurationID = 76;
    public static final int SetCrashConfigurationParameter = 90;
    public static final int SetDataManagerParameter = 82;
    public static final int SetDiagnosisMode = 16;
    public static final int SetFWMode = 66;
    public static final int SetFileType = 58;
    public static final int SetOffset = 50;
    public static final int SetPDURequests = 34;
    public static final int SetUserDatabase = 241;
    public static final int SetWorkingParameters = 80;
    public static final int StartMatrixCalibration = 144;
    public static final int StartRecording = 128;
    public static final int SubscribedObjects = 32;
    public static final int SubscribedObjectsExt = 37;
    public static final int UnsubscribedObjects = 33;
    public static final int UnsubscribedObjectsExt = 33;
    private static final SparseArray<String> _CommandNames;

    static {
        SparseArray<String> sparseArray = new SparseArray<>();
        _CommandNames = sparseArray;
        sparseArray.put(163, "AuthenticationRequest");
        sparseArray.put(48, "BeginFileDownload");
        sparseArray.put(70, "BeginFileUpdate");
        sparseArray.put(69, "BeginSession");
        sparseArray.put(72, "CheckSessionKey");
        sparseArray.put(162, "CreateAuthenticationKey");
        sparseArray.put(51, "EndFileDownload");
        sparseArray.put(75, "EndFileUpdate");
        sparseArray.put(74, "EraseConfigurationFileArea");
        sparseArray.put(79, "GetInterpreterVersion");
        sparseArray.put(49, "GetFileData");
        sparseArray.put(65, "GetFirmwareStatus");
        sparseArray.put(GetHardwareVersion, "GetHardwareVersion");
        sparseArray.put(GetSerialNumber, "GetSerialNumber");
        sparseArray.put(78, "GetSessionID");
        sparseArray.put(GetStatus, "GetStatus");
        sparseArray.put(45, "GetVIN");
        sparseArray.put(17, "GetDiagnosisMode");
        sparseArray.put(71, "SendFileData");
        sparseArray.put(50, "SetOffset");
        sparseArray.put(16, "SetDiagnosisMode");
        sparseArray.put(81, "GetWorkingParameters");
        sparseArray.put(80, "SetWorkingParameters");
        sparseArray.put(46, "GetAvailableParameters");
        sparseArray.put(44, "GetSupportedParameters");
        sparseArray.put(47, "GetObjectsValue");
        sparseArray.put(32, "SubscribedObjects");
        sparseArray.put(33, "UnsubscribedObjects");
        sparseArray.put(43, "GetObjectsValueExt");
        sparseArray.put(37, "SubscribedObjectsExt");
        sparseArray.put(33, "UnsubscribedObjectsExt");
        sparseArray.put(85, "GetSupportedECU");
        sparseArray.put(66, "SetFWMode");
        sparseArray.put(192, "ResetToFactoryDefault");
        sparseArray.put(GetSOSStatus, "GetSOSStatus");
        sparseArray.put(52, "BeginFileDataTrip");
        sparseArray.put(53, "EraseTripDataArea");
        sparseArray.put(54, "GetFileTripData");
        sparseArray.put(GetTripStatus, "GetTripStatus");
        sparseArray.put(83, "GetDataManagerParameters");
        sparseArray.put(82, "SetDataManagerParameter");
        sparseArray.put(76, "SetConfigurationID");
        sparseArray.put(77, "GetConfigurationID");
        sparseArray.put(96, "GetStartTripData");
        sparseArray.put(97, "GetStopTripData");
        sparseArray.put(98, "GetErrorTripData");
        sparseArray.put(99, "GetStatisticsTripData");
        sparseArray.put(55, "BeginFileDataCrash");
        sparseArray.put(57, "GetFileCrashData");
        sparseArray.put(56, "EraseCrashDataArea");
        sparseArray.put(91, "GetCrashConfigurationParameters");
        sparseArray.put(90, "SetCrashConfigurationParameter");
        sparseArray.put(112, "GetExtractionInsertionTime");
        sparseArray.put(144, "StartMatrixCalibration");
        sparseArray.put(145, "GetRotationMatrixStatus");
        sparseArray.put(146, "GetRotationMatrix");
        sparseArray.put(128, "StartRecording");
        sparseArray.put(113, "CheckOBD");
        sparseArray.put(67, "GetDataBaseVersion");
        sparseArray.put(GetSettings, "GetSettings");
        sparseArray.put(73, "GetConfigurationPercent");
        sparseArray.put(100, "GetEraseTripCrashStatus");
        sparseArray.put(114, "GetStandByCrankReport");
        sparseArray.put(115, "GetOperatingCrankReport");
        sparseArray.put(116, "GetLowPowerRecentHistogram");
        sparseArray.put(117, "GetLowPowerTotalHistogram");
        sparseArray.put(129, "AccelerometerSampleTransmission");
        sparseArray.put(130, "SetAccelerometerSampleConfig");
        sparseArray.put(118, "GetLog");
        sparseArray.put(GetSupportedCommands, "GetSupportedCommands");
        sparseArray.put(101, "GetStatisticDiffTripData");
        sparseArray.put(34, "SetPDURequests");
        sparseArray.put(35, "GetPDUResponses");
        sparseArray.put(GetBTMacAddress, "GetBTMacAddress");
        sparseArray.put(58, "SetFileType");
        sparseArray.put(211, "DPM_Call");
        sparseArray.put(DPM_Exit, "DPM_Exit");
        sparseArray.put(DPMT_GetMasterRequest, "DPMT_GetMasterRequest");
        sparseArray.put(DPM_GetStatus, "DPM_GetStatus");
        sparseArray.put(DPMC_GetSupportedDiagnosticProcedures, "DPMC_GetSupportedDiagnosticProcedures");
        sparseArray.put(DPMT_SendSlaveRequest, "DPMT_SendSlaveRequest");
        sparseArray.put(DPMC_SetUnlockCode, "DPMC_SetUnlockCode");
        sparseArray.put(DPMC_SetUserCode, "DPMC_SetUserCode");
        sparseArray.put(DPM_Start, "DPM_Start");
        sparseArray.put(DPM_Stop, "DPM_Stop");
        sparseArray.put(DPMT_SetNotification, "DPMT_SetNotification");
        sparseArray.put(DPMT_NotifySlaveEvent, "DPMT_NotifySlaveEvent");
        sparseArray.put(SetUserDatabase, "SetUserDatabase");
        sparseArray.put(GetUserDatabase, "GetUserDatabase");
        sparseArray.put(DPMC_GetCreationDate, "DPMC_GetCreationDate");
        sparseArray.put(36, "GetNumSubscribedObjects");
        sparseArray.put(86, "LoadDTCbyECUIndex");
        sparseArray.put(87, "ReadDTC");
        sparseArray.put(112, "KeepAlive");
        sparseArray.put(GetFirmwareVersion, "GetFirmwareVersion");
        sparseArray.put(176, "GetRpmSpeedIsValid");
        sparseArray.put(DPM_EraseECUProgrammingReportFile, "DPM_EraseECUProgrammingReportFile");
    }

    public static String getName(Integer num) {
        return num == null ? NO_NAME : _CommandNames.get(num.intValue(), NO_NAME);
    }
}
